In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv('/home/lashvarda/Desktop/covid19/data/raw/covid_19_clean_complete.csv')

In [20]:
df.shape

(49068, 10)

In [21]:
df.columns.tolist()

['Province/State',
 'Country/Region',
 'Lat',
 'Long',
 'Date',
 'Confirmed',
 'Deaths',
 'Recovered',
 'Active',
 'WHO Region']

In [27]:
df.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  str
 1   Country/Region  49068 non-null  str
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  str
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  str
dtypes: float64(2), int64(4), str(4)
memory usage: 3.7 MB

### Missing Values

In [28]:
df.isnull().sum()

Province/State    34404
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             0
Deaths                0
Recovered             0
Active                0
WHO Region            0
dtype: int64

### Duplicates

In [34]:
df.duplicated().sum()

np.int64(0)

### Check the date column

In [38]:
df["Date"].dtype

In [39]:
df["Date"].min()

'2020-01-22'

In [40]:
df["Date"].max()

'2020-07-27'

In [41]:
df["Date"].nunique()

188

In [42]:
df["Date"] = pd.to_datetime(df["Date"])

In [46]:
print("Countries:", df["Country/Region"].nunique())

Countries: 187

In [50]:
print(df["Country/Region"].unique())

<StringArray>
[          'Afghanistan',               'Albania',               'Algeria',
               'Andorra',                'Angola',   'Antigua and Barbuda',
             'Argentina',               'Armenia',             'Australia',
               'Austria',
 ...
               'Burundi',          'Sierra Leone',                'Malawi',
           'South Sudan',        'Western Sahara', 'Sao Tome and Principe',
                 'Yemen',               'Comoros',            'Tajikistan',
               'Lesotho']
Length: 187, dtype: str

In [51]:
df["WHO Region"].value_counts()

WHO Region
Europe                   15040
Western Pacific          10340
Africa                    9024
Americas                  8648
Eastern Mediterranean     4136
South-East Asia           1880
Name: count, dtype: int64

In [52]:
df[["Confirmed", "Deaths", "Recovered", "Active"]].describe()

          Confirmed         Deaths     Recovered        Active
count  4.906800e+04   49068.000000  4.906800e+04  4.906800e+04
mean   1.688490e+04     884.179160  7.915713e+03  8.085012e+03
std    1.273002e+05    6313.584411  5.480092e+04  7.625890e+04
min    0.000000e+00       0.000000  0.000000e+00 -1.400000e+01
25%    4.000000e+00       0.000000  0.000000e+00  0.000000e+00
50%    1.680000e+02       2.000000  2.900000e+01  2.600000e+01
75%    1.518250e+03      30.000000  6.660000e+02  6.060000e+02
max    4.290259e+06  148011.000000  1.846641e+06  2.816444e+06

In [54]:
df[df["Active"] < 0][
    ["Country/Region", "Date", "Confirmed", "Deaths", "Recovered", "Active"]
]

       Country/Region       Date  Confirmed  Deaths  Recovered  Active
16238           China 2020-03-24        168       6        168      -6
16499           China 2020-03-25        168       6        168      -6
16760           China 2020-03-26        168       6        168      -6
17021           China 2020-03-27        168       6        168      -6
17282           China 2020-03-28        168       6        168      -6
17543           China 2020-03-29        168       6        168      -6
17804           China 2020-03-30        168       6        168      -6
18065           China 2020-03-31        168       6        168      -6
18326           China 2020-04-01        168       6        168      -6
32059  United Kingdom 2020-05-23        558      45        515      -2
32320  United Kingdom 2020-05-24        558      45        517      -4
32581  United Kingdom 2020-05-25        559      45        517      -3
33886  United Kingdom 2020-05-30        560      45        525     -10
34147  United Kingdom 2020-05-31        560      45        528     -13
34408  United Kingdom 2020-06-01        560      45        528     -13
34669  United Kingdom 2020-06-02        560      46        528     -14
40080   Liechtenstein 2020-06-23         82       2         81      -1
47192          Uganda 2020-07-20       1069       0       1071      -2

In [56]:
df["Active"].min(), (df["Active"] < 0).sum()

(np.int64(-14), np.int64(18))

In [57]:
country_dates = df.groupby("Country/Region")["Date"].nunique()

print(country_dates.describe())

count    187.0
mean     188.0
std        0.0
min      188.0
25%      188.0
50%      188.0
75%      188.0
max      188.0
Name: Date, dtype: float64

In [62]:
print(country_dates.sort_values().head(20))

Country/Region
Afghanistan            188
Albania                188
Algeria                188
Andorra                188
Angola                 188
Antigua and Barbuda    188
Argentina              188
Armenia                188
Australia              188
Austria                188
Azerbaijan             188
Bahamas                188
Bahrain                188
Bangladesh             188
Barbados               188
Belarus                188
Belgium                188
Belize                 188
Benin                  188
Bhutan                 188
Name: Date, dtype: int64

In [63]:
df.dtypes

Province/State               str
Country/Region               str
Lat                      float64
Long                     float64
Date              datetime64[us]
Confirmed                  int64
Deaths                     int64
Recovered                  int64
Active                     int64
WHO Region                   str
dtype: object

In [64]:
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', 'Date', 'Confirmed',
       'Deaths', 'Recovered', 'Active', 'WHO Region'],
      dtype='str')

In [65]:
df["WHO Region"].unique()

<StringArray>
['Eastern Mediterranean',                'Europe',                'Africa',
              'Americas',       'Western Pacific',       'South-East Asia']
Length: 6, dtype: str

In [66]:
df["Province/State"].nunique()

78

In [68]:
df["Province/State"].dropna().unique()[:30]

<StringArray>
['Australian Capital Territory',              'New South Wales',
           'Northern Territory',                   'Queensland',
              'South Australia',                     'Tasmania',
                     'Victoria',            'Western Australia',
                      'Alberta',             'British Columbia',
                     'Manitoba',                'New Brunswick',
    'Newfoundland and Labrador',                  'Nova Scotia',
                      'Ontario',         'Prince Edward Island',
                       'Quebec',                 'Saskatchewan',
                        'Anhui',                      'Beijing',
                    'Chongqing',                       'Fujian',
                        'Gansu',                    'Guangdong',
                      'Guangxi',                      'Guizhou',
                       'Hainan',                        'Hebei',
                 'Heilongjiang',                        'Henan']
Length: 30, dtype: str

In [69]:
df["Calculated Active"] = (
    df["Confirmed"] - df["Deaths"] - df["Recovered"]
)

In [70]:
df

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region,Calculated Active
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean,0
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe,0
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa,0
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe,0
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa,0
...,...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa,117
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean,375
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa,19
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe,1147
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa,365

### Save the processed CSV

In [71]:
df.to_csv(
    "../data/processed/covid_cleaned.csv",
    index=False
)